#!/usr/bin/env python3
"""Build and validate the two authorised Step 8 real A1-to-A2 handoffs locally."""
from __future__ import annotations
import copy,hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'scripts'))
from validate_a1_to_a2_handoff import candidate_sha256,validate_document
SOURCE=Path('/opt/data/profiles/equinet-a1-icp-discovery/evaluations/step9/final/exports/step9-real-prospects.json');OUT=ROOT/'evaluations/step8/handoffs';APPROVED_AT='2026-08-30T10:42:29Z';TRIGGER_AT='2026-08-30T10:42:30Z';CREATED_AT='2026-08-30T10:42:31Z'
TARGETS={'A1-DARLEY-JONABELL-001':'DARLEY-JONABELL-001','A1-RR-PODIATRY-001':'RR-PODIATRY-001'}
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def gate(i,status,reason,path):return {'gate_id':i,'status':status,'reason':reason,'source_path':path}
def build(candidate,suffix):
 c=copy.deepcopy(candidate);hid=f'A1A2-PILOT-{suffix}';reviewer={'actor_id':'UNITALK-SEVERINE-STEP8','actor_role':'Unitalk Operations A2 Pilot Reviewer','display_name':'Séverine'};c['workflow']={'stage':'approved_for_a2','review_decision':'approved','reviewer':reviewer,'decision_at':APPROVED_AT,'rejection_reason':None};c['recommendation']['next_action']='pass_to_a2';c['recommendation']['notes']='Authorised by Séverine for the bounded Step 8 A2 pilot. This is a Unitalk test authorisation, not outreach or CRM-write approval.';c['updated_at']=APPROVED_AT;c['system_references']['a2_handoff_id']=hid
 statuses=[gate('candidate_schema','pass','Pinned A1 candidate schema and deterministic validation passed.','candidate_snapshot'),gate('human_approval','pass','Séverine authorised this candidate for the bounded A2 pilot.','candidate_snapshot.workflow'),gate('recommendation','pass','Candidate recommendation is pass_to_a2.','candidate_snapshot.recommendation.next_action'),gate('exclusion','pass','Candidate is eligible and not excluded.','candidate_snapshot.qualification.exclusion_status'),gate('minimum_data','pass','A1 minimum data status passed.','candidate_snapshot.qualification.minimum_data_status'),gate('identity_quality','pass','A1 data quality is validated.','candidate_snapshot.data_quality.validation_status'),gate('duplicate_batch','pass','No current-batch duplicate was found.','candidate_snapshot.duplicate_check.batch'),gate('duplicate_exclusion_file','unavailable','No authoritative exclusion file is available.','candidate_snapshot.duplicate_check.provided_exclusion_file'),gate('source_policy','pass','No blocked source supports the candidate.','candidate_snapshot.source_evidence'),gate('scoring_state','pass','A1 deterministic scoring completed.','candidate_snapshot.scoring.status'),gate('audit_identity','pass','A1 audit correlation ID is present.','candidate_snapshot.provenance.audit_correlation_id'),gate('scope_permissions','pass','Manual no-integration pilot keeps writes, providers, outreach and downstream delivery disabled.','constraints'),gate('hubspot_duplicate','unavailable','HubSpot duplicate check is unavailable.','candidate_snapshot.duplicate_check.hubspot'),gate('hubspot_eligibility','unavailable','HubSpot customer, Deal, consent, suppression and owner checks are unavailable.',None)]
 digest=candidate_sha256(c);return {'handoff_schema_version':'1.0.1','handoff_id':hid,'idempotency_key':f'A1A2-IDEMP-PILOT-{suffix}','created_at':CREATED_AT,'source_profile':'equinet-a1-icp-discovery','target_profile':'equinet-a2-enrichment','operating_scope':'manual_no_integration_pilot','delivery_state':'ready_for_delivery','trigger_event':{'event_type':'a1_candidate_approved_for_a2','event_id':f'EVENT-{hid}','occurred_at':TRIGGER_AT,'source_layer':'manual_review_package','source_record_id':c['candidate_id']},'approval_event':{'decision':'approved_for_enrichment','scope':'a2_enrichment','reviewer':reviewer,'decision_at':APPROVED_AT,'source_layer':'manual_review_package','source_record_id':c['candidate_id']},'eligibility':{'status':'eligible','evaluated_at':CREATED_AT,'method_version':'a1-a2-eligibility-1.0.1','gates':statuses,'reasons':['Core A1 approval, quality, source and scoring gates passed.','Unavailable HubSpot and exclusion-file checks are accepted only for this review-only no-integration pilot; outreach remains unavailable.']},'requested_enrichment':{'mode':'default_minimum_package','requested_fields':[],'request_reason':'Bounded Step 8 A2 pilot using A1 evidence first and approved official-site checks only.'},'candidate_snapshot':c,'snapshot_integrity':{'algorithm':'sha256','canonicalization':'json_sorted_utf8_v1','candidate_snapshot_sha256':digest},'integration_availability':{'hubspot_read':'unavailable','staging':'unavailable','workflow':'unavailable','enrichment_provider':'unavailable','email_verification':'unavailable','phone_verification':'unavailable'},'constraints':{'a1_score_mutation_authorized':False,'human_review_required':True,'outreach_authorized':False,'crm_write_authorized':False,'downstream_delivery_authorized':False,'paid_provider_authorized':False,'public_information_creates_consent':False,'external_action_approval_reference':None},'delivery':{'external_event_reference':None,'attempt_count':0,'last_attempt_at':None,'failure_reason':None},'a2_receipt':None,'provenance':{'created_by':'unitalk-a1-a2-handoff-builder','initiated_by':'Séverine Step 8 authorisation','audit_correlation_id':c['provenance']['audit_correlation_id'],'synthetic':False,'tools_used':['deterministic-step8-handoff-builder']}}
def main():
 src=load(SOURCE);index={x['candidate_id']:x['prospect_candidate'] for x in src['candidates']};OUT.mkdir(parents=True,exist_ok=True);results=[]
 for cid,suffix in TARGETS.items():
  doc=build(index[cid],suffix);path=OUT/f'{cid}.handoff.json';path.write_text(json.dumps(doc,indent=2,ensure_ascii=False)+'\n');validation=validate_document(path);results.append({'candidate_id':cid,'handoff_id':doc['handoff_id'],'path':str(path.relative_to(ROOT)),'sha256':sha(path),'valid':validation['valid'],'eligibility':doc['eligibility']['status'],'errors':validation['errors']})
 manifest={'record_type':'step8_real_handoff_package','status':'valid_ready_for_local_a2_intake' if all(x['valid'] for x in results) else 'validation_failed','source_package':str(SOURCE),'source_package_sha256':sha(SOURCE),'approval':{'reviewer':'Séverine','approved_at':APPROVED_AT,'scope':'bounded_a2_pilot_for_two_named_candidates'},'handoffs':results,'hubspot_available':False,'outreach_authorized':False,'paid_provider_authorized':False,'external_actions':0};mp=OUT/'manifest.json';mp.write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n');print(json.dumps(manifest,indent=2,ensure_ascii=False));return 0 if manifest['status']=='valid_ready_for_local_a2_intake' else 1
if __name__=='__main__':raise SystemExit(main())
