#!/usr/bin/env python3
"""Create a hashed Step 8 field receipt from an approved Firecrawl collection record."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];COL=ROOT/'evaluations/step8/collection/collection-manifest.json';POL=ROOT/'foundations/contracts/runtime/a2-step8-pilot-runtime-policy-0.1.0.yaml'
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def canonical_hash(v):return hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def build(candidate_id,field_key,source_url,requested_at):
 m=load(COL);matches=[x for x in m['records'] if x['candidate_id']==candidate_id and x['url']==source_url and x['status']=='collected' and x['robots_allowed']]
 errors=[]
 if len(matches)!=1:errors.append('approved collected page not found uniquely')
 rec=matches[0] if matches else {};allowed={'organisation.stable_type','person.role_title','person.business_email','person.business_phone','organisation.business_email','organisation.business_phone','organisation.public_business_location','organisation.service_area','organisation.disciplines','person.public_profile_urls','organisation.public_profile_urls','person.professional_status'}
 if field_key not in allowed:errors.append('field is not directly collectable from the official-site receipt')
 receipt={'preflight_version':'0.1.0-step8','candidate_id':candidate_id,'source_id':'prospect_official_website','field_key':field_key,'named_need':f'Step 8 verified field observation for {field_key}','execution_mode':'bounded_real_pilot_collection','preflight_status':'completed' if not errors else 'blocked','field_gate':'step8_approved_official_site_field_allowlist','register_status':'conditional','business_approval':'approved_by_equinet','source_rights_preflight':'robots_checked_and_allowed','runtime_readiness':'step8_bounded_pilot','allowed_access_modes':['bounded_public_web_read'],'limits':{'max_pages_per_candidate':5,'max_retry_per_failed_url':1,'concurrency':1},'stop_conditions':['terms_or_robots_denial','login_or_paywall','captcha','http_403','http_429','unexpected_personal_data','scope_or_budget_limit'],'provider_missing_activation_gates':[],'live_runtime_blocks':[],'blocks':errors,'warnings':[],'audit':{'actor_profile':'equinet-a2-enrichment','trigger':'Step 8 bounded official-site collection','timestamp':requested_at,'run_id':f'STEP8-{candidate_id}','source_id':'prospect_official_website','input_scope':{'candidate_id':candidate_id,'field_key':field_key,'named_need':f'Verify {field_key}'},'source_urls':[source_url],'output_reference':rec.get('markdown_path'),'approval_state':'approved_bounded_real_pilot','status':'completed' if not errors else 'blocked','retries':max(0,len(rec.get('attempts',[]))-1),'usage_and_cost':{'api_calls':len(rec.get('attempts',[])),'cost_amount':None,'currency':'USD','cost_status':'unavailable'}},'audit_complete':True,'collection_manifest_sha256':canonical_hash(m),'source_content_sha256':rec.get('markdown_sha256'),'external_call_authorized':False,'external_calls':len(rec.get('attempts',[])),'external_actions':0,'outreach_authorized':False,'crm_write_authorized':False}
 receipt['preflight_sha256']=canonical_hash(receipt);return receipt
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--candidate-id',required=True);p.add_argument('--field-key',required=True);p.add_argument('--source-url',required=True);p.add_argument('--requested-at',default=None);p.add_argument('--output',type=Path,required=True);a=p.parse_args();requested=a.requested_at or datetime.now(timezone.utc).isoformat().replace('+00:00','Z');r=build(a.candidate_id,a.field_key,a.source_url,requested);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'status':r['preflight_status'],'candidate_id':r['candidate_id'],'field_key':r['field_key'],'source_content_sha256':r['source_content_sha256'],'external_calls':r['external_calls'],'external_actions':0,'output':str(a.output)},indent=2));return 0 if not r['blocks'] else 1
if __name__=='__main__':raise SystemExit(main())
