#!/usr/bin/env python3
"""Promote approved Equinet A2 Step 5D Wave 3 for local no-integration use."""
from __future__ import annotations
import hashlib,json,shutil,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];E=ROOT/'evaluations/step5d';TECH=E/'technical-validation.json';BEH=E/'behavioural-validation.json';REVIEW=E/'A2-WAVE-3-REVIEW.md';DRAFT=E/'wave3-draft-package-manifest.json';ACC=E/'acceptance-record.json';PROMO=E/'wave3-promotion-manifest.json';RUNTIME=ROOT/'foundations/contracts/skills/a2-wave3-runtime-manifest-0.1.0.json';ACTIVE=ROOT/'foundations/contracts/A2-ACTIVE-FOUNDATION-MANIFEST.json';SOUL=ROOT/'SOUL.md';ROADMAP=ROOT/'deliverables/A2-DELIVERY-STATUS-AND-ROADMAP.md';AT='2026-08-28T10:15:10Z'
IDS=['a2-evidence-confidence-and-freshness','a2-protected-field-conflict-resolution','a2-data-quality-and-review-readiness','a2-review-package-and-governed-handoffs'];COMMANDS=['scripts/evaluate_a2_evidence_confidence.py','scripts/evaluate_a2_protected_field_action.py','scripts/create_a2_revision.py','scripts/render_and_validate_a2_review_package.py','scripts/build_and_validate_a2_twenty_review.py','scripts/build_and_validate_a2_handoff.py'];SUPPORT=['scripts/a2_wave3_contracts.py'];PINNED=['foundations/contracts/canonical/a2-review-view-spec-0.1.0.json','foundations/contracts/requalification/a2-requalification-package.schema.json','foundations/contracts/twenty/a2-twenty-review-receipt.schema.json','foundations/contracts/twenty/a2-twenty-review-layer-contract-0.1.0-draft.1.json']
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rep(t,o,n):
 if o not in t:raise RuntimeError(f'expected text not found: {o}')
 return t.replace(o,n,1)
def verify():
 t=load(TECH);b=load(BEH);m=load(DRAFT)
 if not t.get('pass') or t.get('deterministic_cases',{}).get('passed')!=21:raise RuntimeError('Wave 3 technical validation not ready')
 if b.get('overall_status')!='pass' or b.get('passed')!=4:raise RuntimeError('Wave 3 behavioural validation not ready')
 if m.get('status')!='ready_for_severine_review_not_approved' or m.get('promotion_performed') is not False:raise RuntimeError('Wave 3 draft state invalid')
 for x in m['files']:
  p=ROOT/x['path']
  if not p.exists() or sha(p)!=x['sha256'] or p.stat().st_size!=x['bytes']:raise RuntimeError(f"draft integrity mismatch: {x['path']}")
def main():
 verify();snap=E/'pre-promotion';sources=[*[ROOT/f'skills/{i}/SKILL.md' for i in IDS],*[ROOT/f'skills/{i}/evals/evals.json' for i in IDS],*[ROOT/x for x in COMMANDS+SUPPORT],SOUL,ROADMAP]
 for p in sources:
  d=snap/p.relative_to(ROOT);d.parent.mkdir(parents=True,exist_ok=True)
  if not d.exists():shutil.copy2(p,d)
 for i in IDS:
  p=ROOT/f'skills/{i}/SKILL.md';t=p.read_text();t=rep(t,'**Version:** `0.1.0-draft.1`','**Version:** `0.1.0`');t=rep(t,'**Status:** `WAVE 3 DRAFT — NOT APPROVED`','**Status:** `WAVE 3 APPROVED — LOCAL NO-INTEGRATION MODE`');p.write_text(t)
 t=REVIEW.read_text();t=rep(t,'**Status:** `READY FOR SÉVERINE REVIEW — NOT APPROVED`',f'**Status:** `APPROVED AND PROMOTED`  \n**Approved by:** Séverine, Unitalk Operations  \n**Approved at:** `{AT}`');REVIEW.write_text(t)
 runtime={'manifest_id':'equinet-a2-wave3-runtime','version':'0.1.0','status':'approved_local_no_integration','approved_at':AT,'approved_by':{'name':'Séverine','role':'Unitalk Operations'},'approved_decisions':[f'W3-{n}' for n in range(1,11)],'skills':[{'skill_id':i,'path':f'skills/{i}/SKILL.md','sha256':sha(ROOT/f'skills/{i}/SKILL.md'),'evals_path':f'skills/{i}/evals/evals.json','evals_sha256':sha(ROOT/f'skills/{i}/evals/evals.json'),'status':'approved_local_no_integration'} for i in IDS],'commands':[{'path':x,'sha256':sha(ROOT/x),'status':'active_local_no_integration'} for x in COMMANDS],'supporting_modules':[{'path':x,'sha256':sha(ROOT/x),'status':'active_local_no_integration'} for x in SUPPORT],'pinned_dependencies':[{'path':x,'sha256':sha(ROOT/x)} for x in PINNED],'validation':{'technical':{'path':str(TECH.relative_to(ROOT)),'sha256':sha(TECH),'deterministic_cases':'21/21 pass'},'behavioural':{'path':str(BEH.relative_to(ROOT)),'sha256':sha(BEH),'scenarios':'4/4 pass'}},'permissions':{'local_file_processing':True,'synthetic_fixture_processing':True,'review_projection':True,'web_access':False,'apify':False,'twenty':False,'hubspot_read':False,'hubspot_write':False,'n8n':False,'outreach':False,'handoff_delivery':False},'destination_status':{'a1_requalification':'prepared_not_delivered','twenty':'prepared_not_delivered','hubspot':'blocked_contract_pending','a3':'blocked_contract_pending','a14':'blocked_contract_pending'},'next_gate':'Step 5E — Full Operational Skills Regression and No-Integration Workflow'};RUNTIME.parent.mkdir(parents=True,exist_ok=True);RUNTIME.write_text(json.dumps(runtime,indent=2,ensure_ascii=False)+'\n')
 soul=SOUL.read_text();anchor='- Wave 2 Runtime Manifest `0.1.0`, approved for local no-integration use.'
 if 'Wave 3 Runtime Manifest `0.1.0`' not in soul:soul=rep(soul,anchor,anchor+'\n- Wave 3 Runtime Manifest `0.1.0`, approved for local no-integration use.')
 soul=rep(soul,'Waves 1 and 2 are approved for local no-integration use. The next delivery gate is Step 5D — Wave 3 Decision, Review and Handoffs. Until all skills, runtime controls, synthetic end-to-end acceptance and a bounded pilot are completed, remain **FOUNDATION CONFIGURED — NOT PILOT-READY**.','Waves 1, 2 and 3 are approved for local no-integration use. The next delivery gate is Step 5E — Full Operational Skills Regression and No-Integration Workflow. Until runtime controls, synthetic end-to-end acceptance and a bounded pilot are completed, remain **FOUNDATION CONFIGURED — NOT PILOT-READY**.');SOUL.write_text(soul)
 road=ROADMAP.read_text();road=rep(road,'**Version:** `1.2.2`','**Version:** `1.2.3`');road=rep(road,'**Next delivery gate:** `Step 5D — Wave 3 decision review and approval`','**Next delivery gate:** `Step 5E — Full Operational Skills Regression and No-Integration Workflow`');road=rep(road,'### Step 5D — Wave 3 Decision, Review and Handoffs — READY FOR SÉVERINE REVIEW / NOT APPROVED','### Step 5D — Wave 3 Decision, Review and Handoffs — COMPLETED / APPROVED');road=rep(road,"- Promotion is pending Séverine's explicit approval of W3-1 through W3-10.",f'- Séverine approved W3-1 through W3-10 on `{AT}`; full Step 5 regression is authorised.');road=rep(road,'Review and approve or amend decisions **W3-1 through W3-10** for Step 5D. After explicit approval, promote Wave 3 atomically, rerun all wave regressions, and open **Step 5E — Full Operational Skills Regression and No-Integration Workflow**.','Build and validate **Step 5E — Full Operational Skills Regression and No-Integration Workflow**, then present the complete Step 5 closure review.');ROADMAP.write_text(road)
 subprocess.run([str(ROOT/'.venv/bin/python'),str(ROOT/'scripts/build_active_foundation_manifest.py')],cwd=ROOT,check=True)
 acc={'record_type':'wave_skill_acceptance','profile':'equinet-a2-enrichment','step':'5D','wave':3,'decision':'approved_and_promoted','approver':{'name':'Séverine','role':'Unitalk Operations'},'approved_at':AT,'approved_decisions':[f'W3-{n}' for n in range(1,11)],'runtime_manifest':str(RUNTIME.relative_to(ROOT)),'runtime_manifest_sha256':sha(RUNTIME),'technical_validation':str(TECH.relative_to(ROOT)),'technical_validation_sha256':sha(TECH),'behavioural_validation':str(BEH.relative_to(ROOT)),'behavioural_validation_sha256':sha(BEH),'active_foundation_manifest':str(ACTIVE.relative_to(ROOT)),'active_foundation_manifest_sha256':sha(ACTIVE),'skill_count':4,'deterministic_cases':'21/21 pass','behavioural_scenarios':'4/4 pass','external_calls':0,'external_actions':0,'profile_status':'FOUNDATION CONFIGURED — NOT PILOT-READY','next_gate':'Step 5E — Full Operational Skills Regression and No-Integration Workflow'};ACC.write_text(json.dumps(acc,indent=2,ensure_ascii=False)+'\n')
 post=E/'post-promotion'
 for p,name in [(SOUL,'SOUL.md'),(ROADMAP,'A2-DELIVERY-STATUS-AND-ROADMAP.md')]:d=post/name;d.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,d)
 immutable=[RUNTIME,*[ROOT/f'skills/{i}/SKILL.md' for i in IDS],*[ROOT/f'skills/{i}/evals/evals.json' for i in IDS],*[ROOT/x for x in COMMANDS+SUPPORT],TECH,BEH,REVIEW,ACC,post/'SOUL.md',post/'A2-DELIVERY-STATUS-AND-ROADMAP.md'];promo={'manifest_id':'equinet-a2-wave3-promotion','version':'0.1.0','status':'approved_and_promoted','approved_decisions':[f'W3-{n}' for n in range(1,11)],'files':[{'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in immutable],'active_foundation_manifest':{'path':str(ACTIVE.relative_to(ROOT)),'sha256':sha(ACTIVE)},'external_actions':0};PROMO.write_text(json.dumps(promo,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'pass':True,'decision':'approved_and_promoted','skills':4,'active_files':len(load(ACTIVE)['active_files']),'next_gate':acc['next_gate'],'external_actions':0},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
