#!/usr/bin/env python3
"""Promote Step 6 for synthetic local testing with real-data gates retained."""
from __future__ import annotations
import hashlib,json,shutil,subprocess
from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1];E=ROOT/'evaluations/step6';CONFIG=ROOT/'config.yaml';DRAFT_POLICY=ROOT/'foundations/contracts/runtime/a2-runtime-policy-0.1.0-draft.1.yaml';FINAL_POLICY=ROOT/'foundations/contracts/runtime/a2-runtime-policy-0.1.0.yaml';TECH=E/'technical-validation.json';REVIEW=E/'A2-STEP-6-REVIEW.md';DRAFT=E/'step6-draft-package-manifest.json';PRIMARY=E/'gateway-smoke/primary-validation.json';ACTIVE=ROOT/'foundations/contracts/A2-ACTIVE-FOUNDATION-MANIFEST.json';SOUL=ROOT/'SOUL.md';ROADMAP=ROOT/'deliverables/A2-DELIVERY-STATUS-AND-ROADMAP.md';ACC=E/'acceptance-record.json';PROMO=E/'step6-promotion-manifest.json';AT='2026-08-29T21:10:52Z'
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rep(t,o,n):
 if o not in t:raise RuntimeError(f'expected text not found: {o}')
 return t.replace(o,n,1)
def main():
 t=load(TECH);m=load(DRAFT);pv=load(PRIMARY)
 if not t.get('pass') or t.get('status')!='ready_for_promotion_synthetic_local_only' or t.get('static_checks')!={'total':14,'passed':14}:raise RuntimeError('Step 6 validation not ready')
 if not (pv.get('routing_configuration_pass') and pv.get('session_response_observed') and pv.get('external_safety_pass') and pv.get('v2_validation',{}).get('business_contract_pass') and pv.get('v2_validation',{}).get('audit_pass')):raise RuntimeError('functional primary smoke not ready for synthetic scope')
 if pv.get('gateway_route_verified') or pv.get('primary_smoke_accepted'):raise RuntimeError('telemetry-pending boundary is not represented correctly')
 if m.get('status')!='ready_for_promotion_synthetic_local_only':raise RuntimeError('Step 6 package status mismatch')
 for x in m['files']:
  p=Path(x['path']) if x['path'].startswith('/') else ROOT/x['path']
  if not p.exists() or sha(p)!=x['sha256'] or p.stat().st_size!=x['bytes']:raise RuntimeError(f"draft hash mismatch: {x['path']}")
 snap=E/'pre-promotion'
 for p in [CONFIG,DRAFT_POLICY,TECH,REVIEW,SOUL,ROADMAP,PRIMARY]:
  d=snap/p.relative_to(ROOT);d.parent.mkdir(parents=True,exist_ok=True)
  if not d.exists():shutil.copy2(p,d)
 policy=yaml.safe_load(DRAFT_POLICY.read_text());policy['policy_version']='0.1.0';policy['status']='approved_for_synthetic_local_testing_gateway_telemetry_pending';policy['approved_at']=AT;policy['approved_by']={'name':'Séverine','role':'Unitalk Operations'};policy['approved_decisions']=[*[f'S6-{n}' for n in range(1,10)],'S6-10-revised'];policy['real_data_activation_gate']['current_status']='blocked_pending_gateway_telemetry_fallback_and_governance';FINAL_POLICY.write_text(yaml.safe_dump(policy,sort_keys=False,allow_unicode=True),encoding='utf-8')
 t['status']='approved_for_synthetic_local_testing_gateway_telemetry_pending';t['approval_required']=False;t['promotion_performed']=True;t['promotion_scope']='synthetic_local_only';t['real_data_authorized']=False;t['next_gate']='Step 7 — Synthetic End-to-End Acceptance';TECH.write_text(json.dumps(t,indent=2,ensure_ascii=False)+'\n')
 review=REVIEW.read_text();review=rep(review,'**Status:** `CONFIGURED — STATIC VALIDATION PASS — LIVE GATEWAY SMOKE PENDING`',f'**Status:** `APPROVED FOR SYNTHETIC LOCAL TESTING — REAL-DATA GATES PENDING`  \n**Approved by:** Séverine, Unitalk Operations  \n**Approved at:** `{AT}`');REVIEW.write_text(review)
 soul=SOUL.read_text();anchor='- Consolidated Step 5 Runtime Manifest `0.1.0`, approved for local no-integration use.'
 if 'A2 Runtime Policy `0.1.0`' not in soul:soul=rep(soul,anchor,anchor+'\n- A2 Runtime Policy `0.1.0`, approved for synthetic local testing; upstream telemetry, fallback and real-data gates pending.')
 soul=rep(soul,'Step 5 operational skills and the local no-integration workflow are approved. The next delivery gate is Step 6 — Model, Tools, Permissions and Quotas. Until runtime controls, synthetic end-to-end acceptance and a bounded pilot are completed, remain **FOUNDATION CONFIGURED — NOT PILOT-READY**.','Step 6 model, tool, permission and quota configuration is approved for synthetic local testing only. The next delivery gate is Step 7 — Synthetic End-to-End Acceptance. Upstream telemetry, fallback verification, provider region/retention and real-data approval remain blocked. The profile remains **FOUNDATION CONFIGURED — NOT PILOT-READY**.');SOUL.write_text(soul)
 road=ROADMAP.read_text();road=rep(road,'**Version:** `1.2.6`','**Version:** `1.2.7`');road=rep(road,'**Next delivery gate:** `Step 6 — live gateway smoke test and configuration approval`','**Next delivery gate:** `Step 7 — Synthetic End-to-End Acceptance`');road=rep(road,'### Step 6 — Model, Tools, Permissions and Quotas — CONFIGURED / STATIC VALIDATION PASS / LIVE GATEWAY SMOKE PENDING','### Step 6 — Model, Tools, Permissions and Quotas — APPROVED FOR SYNTHETIC LOCAL TESTING / REAL-DATA GATES PENDING');road=rep(road,'Run a real primary-model smoke test from a session launched with `equinet-a2-enrichment`, then run a controlled fallback-route test. After both receipts are recorded, present **S6-1 through S6-10** for promotion.','Build and validate **Step 7 — Synthetic End-to-End Acceptance** using synthetic data only.');ROADMAP.write_text(road)
 subprocess.run([str(ROOT/'.venv/bin/python'),str(ROOT/'scripts/build_active_foundation_manifest.py')],cwd=ROOT,check=True)
 decisions=[*[f'S6-{n}' for n in range(1,10)],'S6-10-revised'];acc={'record_type':'step6_runtime_acceptance','profile':'equinet-a2-enrichment','step':'6','decision':'approved_for_synthetic_local_testing','approver':{'name':'Séverine','role':'Unitalk Operations'},'approved_at':AT,'approved_decisions':decisions,'config':str(CONFIG.relative_to(ROOT)),'config_sha256':sha(CONFIG),'runtime_policy':str(FINAL_POLICY.relative_to(ROOT)),'runtime_policy_sha256':sha(FINAL_POLICY),'technical_validation':str(TECH.relative_to(ROOT)),'technical_validation_sha256':sha(TECH),'primary_validation':str(PRIMARY.relative_to(ROOT)),'primary_validation_sha256':sha(PRIMARY),'active_foundation_manifest':str(ACTIVE.relative_to(ROOT)),'active_foundation_manifest_sha256':sha(ACTIVE),'primary_functional_smoke':'passed_for_synthetic','primary_upstream_telemetry':'pending','fallback_route':'configured_not_tested','real_data_authorized':False,'external_actions':0,'profile_status':'FOUNDATION CONFIGURED — NOT PILOT-READY','next_gate':'Step 7 — Synthetic End-to-End Acceptance'};ACC.write_text(json.dumps(acc,indent=2,ensure_ascii=False)+'\n')
 post=E/'post-promotion'
 for p,name in [(SOUL,'SOUL.md'),(ROADMAP,'A2-DELIVERY-STATUS-AND-ROADMAP.md')]:d=post/name;d.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,d)
 immutable=[CONFIG,FINAL_POLICY,TECH,REVIEW,PRIMARY,ACC,post/'SOUL.md',post/'A2-DELIVERY-STATUS-AND-ROADMAP.md'];promo={'manifest_id':'equinet-a2-step6-promotion','version':'0.1.0','status':'approved_for_synthetic_local_testing','approved_decisions':decisions,'files':[{'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in immutable],'active_foundation_manifest':{'path':str(ACTIVE.relative_to(ROOT)),'sha256':sha(ACTIVE)},'real_data_authorized':False,'external_actions':0};PROMO.write_text(json.dumps(promo,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'pass':True,'decision':acc['decision'],'primary_functional_smoke':'passed','upstream_telemetry':'pending','fallback':'configured_not_tested','real_data_authorized':False,'active_files':len(load(ACTIVE)['active_files']),'next_gate':acc['next_gate']},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
