#!/usr/bin/env python3
"""Run the complete local Step 11 website-first acceptance flow."""
from __future__ import annotations
import json,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];F=ROOT/'evaluations/step11/fixtures';W=ROOT/'evaluations/step11/work';PY=sys.executable
def run(*args):
 p=subprocess.run([PY,*map(str,args)],cwd=ROOT,capture_output=True,text=True)
 if p.returncode:raise RuntimeError(f'{args}: {p.stdout}\n{p.stderr}')
 return p
def load(path):return json.loads(Path(path).read_text())
def main():
 if W.exists():shutil.rmtree(W)
 W.mkdir(parents=True);steps=[]
 def step(name,*args):run(*args);steps.append(name)
 step('site_plan','scripts/build_official_site_plan.py',F/'firecrawl/plan-input.json','--output',W/'site-plan.json')
 step('firecrawl_fixture','scripts/firecrawl_official_site_fetch.py',W/'site-plan.json','--fixture',F/'firecrawl/happy-path.json','--output',W/'site-fetch.json')
 step('site_observations','scripts/extract_official_site_observations.py',W/'site-fetch.json','--output',W/'site-observations.json')
 step('website_packet','scripts/build_website_decision_packet.py',W/'site-observations.json','--output',W/'website-packet-preliminary.json')
 preliminary=load(W/'website-packet-preliminary.json');proposal_review={'run_id':preliminary['run_id'],'company_id':preliminary['company_id'],'reviewed_block_ids':[row['block_id'] for row in preliminary.get('person_evidence_blocks',[])],'proposals':[]};(W/'website-person-proposals.json').write_text(json.dumps(proposal_review,indent=2)+'\n')
 step('website_person_proposals','scripts/validate_website_person_observation_proposals.py',W/'website-packet-preliminary.json',W/'website-person-proposals.json','--output',W/'website-packet.json')
 step('website_decisions','scripts/validate_website_decisions.py',W/'website-packet.json',F/'firecrawl/website-decisions.json','--output',W/'website-validation.json')
 step('website_people','scripts/build_website_people_contact_batch.py',W/'website-packet.json',W/'website-validation.json','--run-id','step11-fixture-run','--output',W/'website-selected-people.json')
 step('contact_fixture','scripts/fullenrich_contact_enrichment.py',W/'website-selected-people.json','--fixture',F/'firecrawl/contact-provider.json','--output',W/'website-contact-results.json')
 # Company merge request from validated Company-attributed contacts/socials.
 val=load(W/'website-validation.json');base=load(F/'company_merge/merge-request.json')['baseline']
 step('assemble_company_merge','scripts/assemble_company_contact_merge_request.py',F/'firecrawl/companies-baseline.json',W/'website-validation.json','--company-id','company-fixture-001','--run-id','step11-fixture-run','--output',W/'company-merge-request.json')
 step('company_merge','scripts/build_company_contact_merge_plan.py',W/'company-merge-request.json','--output',W/'company-merge-plan.json')
 # Build reviewed synthetic write proposal from contact results.
 contact=load(W/'website-contact-results.json');people=[]
 for row in contact['results']:
  profile=row.get('profile') or {};people.append({'source_kind':row.get('source_kind') or 'new','selection_stage':'website','twenty_person_id':row.get('twenty_person_id'),'website_person_id':row.get('website_person_id'),'provider_person_id':row.get('provider_person_id'),'full_name':row.get('source_full_name') or profile.get('full_name'),'first_name':profile.get('first_name'),'last_name':profile.get('last_name'),'exact_current_role':row.get('exact_current_role'),'merged_work_emails':[x for x in [row.get('website_work_email'),row.get('work_email')] if x],'merged_phones':[x for x in [row.get('website_phone'),row.get('mobile_phone')] if x],'statuses':{'identity':'VERIFIED','role':'CURRENT_AT_COMPANY','priority':row.get('selected_target_priority') or 'UNKNOWN','company_match':'CONFIRMED','enrichment':'ENRICHED' if row.get('work_email') or row.get('mobile_phone') else 'PARTIAL'},'field_decisions':{'exact_current_role':'add' if row.get('exact_current_role') else 'no_change'}})
 merge=load(W/'company-merge-plan.json');proposal={'run_id':'step11-fixture-run','company_id':val['company_id'],'enrichment_version':'step11-0.1.0','company_final_status':'PARTIALLY_ENRICHED','company_merge':{'baseline':base,'baseline_sha256':merge['baseline_sha256'],'company_field_updates':merge['company_field_updates']},'resolved_people':people};(W/'write-proposal.json').write_text(json.dumps(proposal,indent=2)+'\n');step('write_plan','scripts/build_twenty_enrichment_write_plan.py',W/'write-proposal.json','--output',W/'write-plan.json');step('write_dry','scripts/push_twenty_enrichment.py',W/'write-plan.json','--output',W/'write-dry-run.json')
 # Facebook fallback fixture path.
 step('apify_requests','scripts/build_apify_facebook_requests.py',F/'apify/companies.json','--output',W/'apify-requests.json');step('apify_fixture','scripts/apify_facebook_page_contact.py',W/'apify-requests.json','--fixture',F/'apify/provider-success.json','--poll-interval','0','--output',W/'apify-raw-results.json');step('apify_validation','scripts/validate_apify_facebook_results.py',W/'apify-raw-results.json','--output',W/'apify-results.json')
 apify_valid=load(W/'apify-results.json');empty_base={'email':{'primaryEmail':'','additionalEmails':[]},'phone':{'primaryPhoneNumber':'','primaryPhoneCountryCode':'','primaryPhoneCallingCode':'','additionalPhones':[]},'linkedinLink':{'primaryLinkUrl':'','primaryLinkLabel':'','secondaryLinks':[]},'facebook':{'primaryLinkUrl':'','primaryLinkLabel':'','secondaryLinks':[]},'instagram':{'primaryLinkUrl':'','primaryLinkLabel':'','secondaryLinks':[]},'youtube':{'primaryLinkUrl':'','primaryLinkLabel':'','secondaryLinks':[]},'tiktok':{'primaryLinkUrl':'','primaryLinkLabel':'','secondaryLinks':[]},'xTwitter':{'primaryLinkUrl':'','primaryLinkLabel':'','secondaryLinks':[]}};apify_obs=[]
 for x in apify_valid['append_candidates']:apify_obs.append({'field':'email' if x['field_key'].endswith('email') else 'phone','value':x['value'],'accepted':True,'source':'apify_facebook_page_contact_information','source_url':x['source_url'],'evidence_refs':[x['candidate_id']]})
 apify_merge_request={'run_id':'step11-fixture-run','company_id':'company-trigger','baseline':empty_base,'observations':apify_obs};(W/'apify-company-merge-request.json').write_text(json.dumps(apify_merge_request,indent=2)+'\n');step('apify_company_merge','scripts/build_company_contact_merge_plan.py',W/'apify-company-merge-request.json','--output',W/'apify-company-merge-plan.json')
 # Schemas.
 pairs=[('a2-official-site-plan-0.1.0.schema.json',W/'site-plan.json'),('a2-firecrawl-official-site-results-0.1.0.schema.json',W/'site-fetch.json'),('a2-official-site-observations-0.1.0.schema.json',W/'site-observations.json'),('a2-website-decision-packet-0.1.0.schema.json',W/'website-packet.json'),('a2-website-person-observation-proposals-0.1.0.schema.json',W/'website-person-proposals.json'),('a2-website-decisions-0.1.0.schema.json',W/'website-validation.json'),('a2-company-contact-merge-plan-0.1.0.schema.json',W/'company-merge-plan.json'),('a2-apify-facebook-requests-0.1.0.schema.json',W/'apify-requests.json'),('a2-apify-facebook-results-0.1.0.schema.json',W/'apify-results.json'),('a2-write-proposal-0.1.3.schema.json',W/'write-proposal.json')]
 for schema,artifact in pairs:step('schema_'+schema,'scripts/validate_a2_integration_artifact.py',ROOT/'foundations/contracts/integrations/schemas'/schema,artifact)
 fetch=load(W/'site-fetch.json');obs=load(W/'site-observations.json');selected=load(W/'website-selected-people.json');apify=load(W/'apify-results.json');apify_merge=load(W/'apify-company-merge-plan.json');plan=load(W/'write-plan.json');dry=load(W/'write-dry-run.json');assertions={'five_pages':fetch['page_count']==5,'zero_live_web_calls':fetch['external_calls']==0,'all_socials':{x['platform'] for x in obs['social_links']}=={'facebook','instagram','youtube','linkedin','tiktok','x'},'two_people':len(selected['selected_people'])+len(selected['complete_people'])==2,'contact_enriched':len(contact['results'])==2,'company_merge':len(merge['company_field_updates'])>=2,'facebook_candidates':len(apify['append_candidates'])==2,'facebook_company_append':set(apify_merge['company_field_updates'])=={'email','phone'},'company_merge_first':plan['operations'][0]['operation_type']=='update_company_fields','status_last':plan['operations'][-1]['operation_type']=='update_company_status','dry_run':dry['status']=='dry_run' and dry['external_writes']==0}
 out={'suite':'step11_website_first_synthetic_acceptance','status':'pass' if all(assertions.values()) else 'fail','steps':steps,'assertions':assertions,'external_calls':0,'external_writes':0,'failures':[k for k,v in assertions.items() if not v]};(ROOT/'evaluations/step11/synthetic-acceptance.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));return 0 if out['status']=='pass' else 1
if __name__=='__main__':raise SystemExit(main())
