#!/usr/bin/env python3
"""Run Jonabell Stage 2 evidence/confidence for the three accepted Stage 1 observations."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];B=ROOT/'evaluations/step8/pilot/A1-DARLEY-JONABELL-001';BATCH=B/'observation-batch.json';VALID=B/'validated-observations.json';DECISION=B/'target-role-priority-review.json';OUT=B/'evidence-confidence';MANIFEST=OUT/'manifest.json';PY=ROOT/'.venv/bin/python'
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 batch=load(BATCH);valid=load(VALID);decision=load(DECISION)
 if decision.get('decision')!='approved' or decision.get('approved_value')!='secondary':raise RuntimeError('relationship classification review is missing')
 raw={x['observation_id']:x for x in batch['observations']};accepted=[x for x in valid['observations'] if x['action']=='accept_for_wave3_evidence_assessment'];OUT.mkdir(parents=True,exist_ok=True);results=[]
 for item in accepted:
  source=raw[item['observation_id']];field=item['field_key'];freshness='current' if field=='organisation.stable_type' else 'current_official_undated';req={'evidence_id':item['evidence_id'],'field_assessment_id':item['field_assessment_candidate']['field_assessment_id'],'source_id':'prospect_official_website','claim_key':field,'normalised_value':item['normalised_value'],'source_references':[source['source_url'],source['source_preflight']['audit']['output_reference']],'source_preflight':source['source_preflight'],'identity_match':'exact','claim_directness':'direct_fact','freshness':freshness,'corroboration':'authoritative_or_primary_sufficient','consistency':'no_conflict','required_claim':True};slug=field.replace('.','-');rp=OUT/f'{slug}.request.json';op=OUT/f'{slug}.result.json';rp.write_text(json.dumps(req,indent=2,ensure_ascii=False)+'\n');p=subprocess.run([str(PY),str(ROOT/'scripts/evaluate_a2_evidence_confidence.py'),str(rp),'--output',str(op)],cwd=ROOT,capture_output=True,text=True);result=load(op) if op.exists() else {'errors':[p.stdout,p.stderr]};passed=p.returncode==0 and result.get('verification_status')=='verified' and result.get('confidence_level')=='high' and result.get('external_actions')==0;results.append({'field_key':field,'request_path':str(rp.relative_to(ROOT)),'request_sha256':sha(rp),'result_path':str(op.relative_to(ROOT)),'result_sha256':sha(op) if op.exists() else None,'confidence_score':result.get('confidence_score'),'confidence_level':result.get('confidence_level'),'verification_status':result.get('verification_status'),'freshness_status':result.get('freshness_status'),'passed':passed,'errors':result.get('errors',[])})
 manifest={'record_type':'step8_jonabell_evidence_confidence','candidate_id':'A1-DARLEY-JONABELL-001','status':'pass' if all(x['passed'] for x in results) and len(results)==3 else 'failed','stage1_validated_observations_sha256':sha(VALID),'target_role_review_sha256':sha(DECISION),'results':results,'relationship_target_role_priority':{'value':'secondary','source':'human_review','confidence_scoring_not_applicable':True},'a1_score_changed':False,'canonical_record_mutated':False,'external_actions':0};MANIFEST.write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n');print(json.dumps(manifest,indent=2,ensure_ascii=False));return 0 if manifest['status']=='pass' else 1
if __name__=='__main__':raise SystemExit(main())
