#!/usr/bin/env python3
"""Run the Step 7 representative synthetic acceptance suite."""
from __future__ import annotations
import hashlib,json,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];E=ROOT/'evaluations/step7';OUT=E/'deterministic-acceptance.json';W1=ROOT/'evaluations/step5b/fixtures/wave1-cases.json';W2=ROOT/'evaluations/step5c/fixtures/wave2-cases.json';W3=ROOT/'evaluations/step5d/fixtures/wave3-cases.json';PY=ROOT/'.venv/bin/python'
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def run(args):return subprocess.run([str(PY),*args],cwd=ROOT,capture_output=True,text=True)
def main():
 E.mkdir(parents=True,exist_ok=True);scenarios=[];errors=[]
 for scenario,expected in [('farrier_review','blocked_contract_pending'),('horse_owner_requalification','prepared_not_delivered')]:
  d=E/'workflows'/scenario
  if d.exists():shutil.rmtree(d)
  p=run(['scripts/run_a2_no_integration_workflow.py','--scenario',scenario,'--output-dir',str(d)]);r=load(d/'workflow-result.json');handoff=load(d/'governed-handoff.json');review=load(d/'review-result.json');ok=p.returncode==0 and r['status']=='pass' and r['operator_count']==14 and review['valid'] is True and handoff['status']==expected and handoff['delivered'] is False and r['external_actions']==0;scenarios.append({'scenario':scenario,'expected_outcome':expected,'observed_outcome':handoff['status'],'operator_count':r['operator_count'],'review_package_valid':review['valid'],'human_decision':'pending_or_synthetic_fixture_only','external_actions':0,'passed':ok,'result_path':str((d/'workflow-result.json').relative_to(ROOT))});errors.append(f'workflow failed: {scenario}') if not ok else None
 f1=load(W1)
 for name,expected in [('possible-duplicate-hold','hold'),('confirmed-duplicate-block','blocked')]:
  case=next(x for x in f1['eligibility_cases'] if x['name']==name);pfile=E/f'{name}.input.json';ofile=E/f'{name}.json';pfile.write_text(json.dumps(case['request'],indent=2)+'\n');p=run(['scripts/evaluate_a2_duplicate_eligibility.py',str(pfile),'--output',str(ofile)]);r=load(ofile);ok=p.returncode==0 and r['a2_eligibility_status']==expected and r['external_actions']==0;scenarios.append({'scenario':name,'expected_outcome':expected,'observed_outcome':r['a2_eligibility_status'],'human_decision':'pending','external_actions':0,'passed':ok,'result_path':str(ofile.relative_to(ROOT))});errors.append(f'case failed: {name}') if not ok else None
 f3=load(W3);case=next(x for x in f3['protected_cases'] if x['name']=='authoritative-block');pfile=E/'authoritative-conflict.input.json';ofile=E/'authoritative-conflict.json';pfile.write_text(json.dumps(case['request'],indent=2)+'\n');p=run(['scripts/evaluate_a2_protected_field_action.py',str(pfile),'--output',str(ofile)]);r=load(ofile);ok=p.returncode==0 and r['recommended_action']=='preserve_authoritative_and_block' and r['external_write_allowed'] is False;scenarios.append({'scenario':'authoritative-control-conflict','expected_outcome':'preserve_authoritative_and_block','observed_outcome':r['recommended_action'],'human_decision':'pending','external_actions':0,'passed':ok,'result_path':str(ofile.relative_to(ROOT))});errors.append('authoritative conflict failed') if not ok else None
 f2=load(W2);case=next(x for x in f2['source_cases'] if x['name']=='official-site-social-opening-blocked');req=dict(case['request']);req.update({'actor_profile':'equinet-a2-enrichment','trigger':'Step 7 prohibited action test','requested_at':'2026-08-29T21:20:00Z','run_id':'STEP7-BLOCK-001'});pfile=E/'prohibited-social.input.json';ofile=E/'prohibited-social.json';pfile.write_text(json.dumps(req,indent=2)+'\n');p=run(['scripts/preflight_a2_source_action.py',str(pfile),'--output',str(ofile)]);r=load(ofile);ok=p.returncode==0 and r['preflight_status']=='blocked' and 'opening_linked_social_profile_is_not_authorised' in r['blocks'] and r['external_actions']==0;scenarios.append({'scenario':'prohibited-social-profile-opening','expected_outcome':'blocked','observed_outcome':r['preflight_status'],'human_decision':'not_applicable','external_actions':0,'passed':ok,'result_path':str(ofile.relative_to(ROOT))});errors.append('prohibited source action failed') if not ok else None
 output_files=[]
 for scenario in ['farrier_review','horse_owner_requalification']:
  d=E/'workflows'/scenario/'review-package';manifest=load(d/'manifest.json')
  for x in manifest['outputs']:
   p=Path(x['path']);output_files.append({'scenario':scenario,'path':str(p.relative_to(ROOT)) if p.is_relative_to(ROOT) else str(p),'sha256':sha(p),'bytes':p.stat().st_size})
 formats={'markdown':sum(x['path'].endswith('.md') for x in output_files),'csv':sum(x['path'].endswith('.csv') for x in output_files),'xlsx':sum(x['path'].endswith('.xlsx') for x in output_files)}
 result={'step':'7','suite':'representative_synthetic_acceptance','version':'0.1.0-draft.1','status':'deterministic_pass_profile_invocation_pending' if not errors else 'validation_failed','scenario_count':len(scenarios),'passed':sum(x['passed'] for x in scenarios),'scenarios':scenarios,'export_files':output_files,'export_formats':formats,'all_records_synthetic':True,'human_decisions_remain_pending_or_fixture_only':True,'model_usage':{'model_calls':0,'tokens':'not_applicable_deterministic_suite','cost_usd':'not_applicable_deterministic_suite'},'profile_level_invocation':'pending','external_calls':0,'external_actions':0,'profile_status':'FOUNDATION CONFIGURED — NOT PILOT-READY','failures':errors,'pass':not errors};OUT.write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'pass':result['pass'],'scenarios':f"{result['passed']}/{result['scenario_count']}",'formats':formats,'profile_invocation':'pending','external_actions':0,'failures':errors},indent=2));return 0 if not errors else 1
if __name__=='__main__':raise SystemExit(main())
