#!/usr/bin/env python3
"""Run targeted Step 5D behavioural scenarios through exact operator commands."""
from __future__ import annotations
import json,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];FIX=ROOT/'evaluations/step5d/fixtures/wave3-cases.json';OUT=ROOT/'evaluations/step5d/behavioural-validation.json'
def run(args:list[str]):
 p=subprocess.run([sys.executable,*args],cwd=ROOT,capture_output=True,text=True);data=json.loads(p.stdout);return p.returncode,data
def main():
 f=json.loads(FIX.read_text());sc=[]
 with tempfile.TemporaryDirectory(prefix='a2-w3-beh-') as n:
  t=Path(n);req=dict(f['evidence_cases'][0]['request']);preq={'candidate_id':'SYN-W3-BEH','operating_scope':'synthetic_test','source_id':req['source_id'],'field_key':req['claim_key'],'named_need':'Wave 3 evidence assessment','execution_mode':'local_fixture_simulation','fixture_is_synthetic':True,'fixture_reference':'fixtures://w3-beh-evidence','official_site_check':'completed_fixture','actor_profile':'equinet-a2-enrichment','trigger':'Wave 3 evidence assessment','requested_at':'2026-08-27T14:50:00Z','run_id':'W3-BEH-001'};pf=t/'preflight.json';pf.write_text(json.dumps(preq));_,receipt=run(['scripts/preflight_a2_source_action.py',str(pf)]);req['source_preflight']=receipt;e=t/'e.json';e.write_text(json.dumps(req));rc,r=run(['scripts/evaluate_a2_evidence_confidence.py',str(e)]);checks={'verified_high':rc==0 and r['verification_status']=='verified' and r['confidence_level']=='high','no_score_change':r['a1_score_changed'] is False,'zero_actions':r['external_actions']==0};sc.append({'skill_id':'a2-evidence-confidence-and-freshness','status':'pass' if all(checks.values()) else 'fail','checks':checks})
  p=t/'p.json';p.write_text(json.dumps(f['protected_cases'][2]['request']));rc,r=run(['scripts/evaluate_a2_protected_field_action.py',str(p)]);checks={'authoritative_preserved':rc==0 and r['recommended_action']=='preserve_authoritative_and_block','no_write':r['external_write_allowed'] is False,'zero_actions':r['external_actions']==0};sc.append({'skill_id':'a2-protected-field-conflict-resolution','status':'pass' if all(checks.values()) else 'fail','checks':checks})
  prev=ROOT/f['records']['review_previous'];cur=ROOT/f['records']['review_current'];rc,r=run(['scripts/create_a2_revision.py',str(prev),str(cur)]);checks={'revision_valid':rc==0 and r['valid'] is True,'lineage':r['prior_revision_id']!=r['record_revision_id'],'zero_actions':r['external_actions']==0};sc.append({'skill_id':'a2-data-quality-and-review-readiness','status':'pass' if all(checks.values()) else 'fail','checks':checks})
  out=t/'review';rc,review=run(['scripts/render_and_validate_a2_review_package.py',str(cur),'--previous-record',str(prev),'--output-dir',str(out)]);rq=ROOT/f['records']['requalification_current'];rqp=ROOT/f['records']['requalification_previous'];rc2,h=run(['scripts/build_and_validate_a2_handoff.py',str(rq),'--previous-record',str(rqp),'--destination','a1_requalification']);checks={'review_package_valid':rc==0 and review['valid'] is True,'a1_handoff_prepared':rc2==0 and h['status']=='prepared_not_delivered','not_delivered':h['delivered'] is False,'zero_actions':review['external_actions']==h['external_actions']==0};sc.append({'skill_id':'a2-review-package-and-governed-handoffs','status':'pass' if all(checks.values()) else 'fail','checks':checks})
 passed=sum(x['status']=='pass' for x in sc);result={'record_type':'wave3_targeted_behavioural_validation','profile':'equinet-a2-enrichment','step':'5D','wave':3,'method':'exact operator commands against synthetic fixtures in temporary directories','scenarios':sc,'scenario_count':len(sc),'passed':passed,'failed':len(sc)-passed,'overall_status':'pass' if passed==len(sc) else 'fail','external_calls':0,'external_actions':0};OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n');print(json.dumps(result,indent=2,ensure_ascii=False));return 0 if result['overall_status']=='pass' else 1
if __name__=='__main__':raise SystemExit(main())
