#!/usr/bin/env python3
"""Validate Equinet A2 Step 6 model, tool, permission and quota configuration."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1];CONFIG=ROOT/'config.yaml';POLICY=ROOT/'foundations/contracts/runtime/a2-runtime-policy-0.1.0-draft.1.yaml';DEFAULT=Path('/opt/data/config.yaml');STEP5=ROOT/'evaluations/step5e/acceptance-record.json';E=ROOT/'evaluations/step6';OUT=E/'technical-validation.json';REVIEW=E/'A2-STEP-6-REVIEW.md';MANIFEST=E/'step6-draft-package-manifest.json';PRIMARY_RESULT=E/'gateway-smoke/primary-result.json';PRIMARY_V2=E/'gateway-smoke/primary-result-v2.json';PRIMARY_VALIDATION=E/'gateway-smoke/primary-validation.json';SMOKE_VALIDATOR=ROOT/'scripts/validate_step6_gateway_smoke.py'
def load_yaml(p):return yaml.safe_load(p.read_text(encoding='utf-8'))
def load_json(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 failures=[];checks={};c=load_yaml(CONFIG);p=load_yaml(POLICY);d=load_yaml(DEFAULT);s5=load_json(STEP5)
 checks['step5_approved']=s5.get('decision')=='approved_and_promoted' and s5.get('next_gate')=='Step 6 — Model, Tools, Permissions and Quotas'
 checks['unitalk_gateway_pattern']=c['model'].get('provider')==d['model'].get('provider')=='openai-api' and c['model'].get('provider_name')==d['model'].get('provider_name')=='litellm-unitalk' and 'api_key' not in c['model']
 checks['primary_model']=c['model'].get('default')=='deepseek-v4-flash' and p['model_routing']['primary']['upstream_provider']=='microsoft_azure'
 checks['fallback_model']=c.get('fallback_providers')==[{'provider':'openai-api','model':'Gemini 3.7 Flash'}] and p['model_routing']['fallback']['upstream_provider']=='google'
 checks['fallback_policy']=p['model_routing']['fallback']['maximum_activations_per_turn']==1 and p['model_routing']['fallback']['trigger']=='primary_technical_failure_only' and p['fallback_policy']['preserve_same_permissions_and_context'] is True
 checks['native_controls']=c['model'].get('max_tokens')==4000 and c['agent']=={'max_turns':50,'api_max_retries':1,'reasoning_effort':'medium'}
 expected={'clarify','code_execution','file','skills','terminal','todo'};actual=set(c['platform_toolsets']['cli']);checks['local_tool_allowlist']=actual==expected and not actual.intersection({'web','browser','computer_use','memory','session_search','delegation','cronjob'})
 ip=p['integration_permissions'];checks['integrations_disabled']=all(v is False for v in ip.values())
 q=p['quotas'];checks['local_quotas']=q['candidates_per_synthetic_run']=={'default':10,'maximum':10} and q['concurrency']==1 and q['external_api_spend_usd']==0 and q['provider_calls_per_run']==0 and q['web_calls_per_run']==0
 bg=p['budget_governance'];checks['budget_governance']=bg['budget_scope']=='unitalk_mustad_global' and bg['initial_prepaid_credit_usd']==5000 and [bg['warning_percent'],bg['escalation_percent'],bg['hard_stop_percent']]==[50,80,100] and bg['negative_balance_permitted'] is False
 checks['access_roles']=len(p['access_control']['authorised_operator_roles'])==3 and p['access_control']['source_policy_approver']['named_approver']=='Séverine'
 checks['journalisation']=p['journalisation']['required'] is True and len(p['journalisation']['required_fields'])==12 and p['journalisation']['credentials_logged'] is False
 checks['pending_values_explicit']=p['model_routing']['primary']['processing_region']=='pending_gateway_confirmation' and p['model_routing']['fallback']['processing_region']=='pending_gateway_confirmation' and p['journalisation']['retention_policy']=='pending_dpa_confirmation' and p['budget_governance']['a2_specific_allocation_usd'] is None
 checks['no_secret_in_profile_config']='api_key' not in c.get('model',{}) and 'base_url' not in c.get('model',{})
 for k,v in checks.items():
  if not v:failures.append(f'check failed: {k}')
 primary_validation=load_json(PRIMARY_VALIDATION) if PRIMARY_VALIDATION.exists() else None
 pv2=(primary_validation or {}).get('v2_validation',{});functional_primary=bool(primary_validation and primary_validation.get('routing_configuration_pass') and primary_validation.get('session_response_observed') and primary_validation.get('external_safety_pass') and pv2.get('business_contract_pass') and pv2.get('audit_pass'))
 live={'primary_model_call':'functional_smoke_pass_upstream_telemetry_pending' if functional_primary else 'response_observed_gateway_telemetry_pending' if primary_validation and primary_validation.get('session_response_observed') else 'not_executed','primary_functional_smoke_accepted_for_synthetic':functional_primary,'primary_upstream_route_verified':bool(primary_validation and primary_validation.get('gateway_route_verified')),'primary_validation_reference':str(PRIMARY_VALIDATION.relative_to(ROOT)) if primary_validation else None,'fallback_model_call':'configured_not_tested','promotion_blocked_for_synthetic':not functional_primary,'real_data_activation_blocked':True,'fallback_route_test_required_before_real_data':True}
 result={'step':'6','version':'0.1.0-draft.1','status':'ready_for_promotion_synthetic_local_only' if not failures and functional_primary else 'configured_static_validation_pass_live_gateway_smoke_pending' if not failures else 'validation_failed','profile':'equinet-a2-enrichment','checks':checks,'static_checks':{'total':len(checks),'passed':sum(checks.values())},'model_routing':{'primary':'deepseek-v4-flash','primary_upstream':'microsoft_azure','fallback':'Gemini 3.7 Flash','fallback_upstream':'google','gateway':'litellm-unitalk'},'live_route_validation':live,'enabled_toolsets':sorted(actual),'integration_permissions':ip,'quota_state':{'configured_local_limits':True,'cumulative_token_thresholds':'pending_baseline','budget_scope':'unitalk_mustad_global'},'external_calls':0,'external_actions':0,'approval_required':True,'promotion_performed':False,'promotion_scope':'synthetic_local_only','real_data_authorized':False,'profile_status':'FOUNDATION CONFIGURED — NOT PILOT-READY','next_gate':'Step 7 — Synthetic End-to-End Acceptance after Step 6 approval','failures':failures,'pass':not failures};E.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n')
 v2=(primary_validation or {}).get('v2_validation',{});primary_note=('A primary session response was observed and the V2.1 contract-bound business task and audit both passed. LiteLLM request telemetry remains unavailable, so the upstream route is configuration-confirmed but not independently verified.' if v2.get('business_contract_pass') and v2.get('audit_pass') else 'A primary session response was observed and the business task passed, but its audit remains incomplete.' if v2.get('business_contract_pass') else 'A primary session response was observed, but the smoke receipt remains incomplete.' if primary_validation else 'No primary session response has been recorded.')
 decisions=[('S6-1','Route A2 through the Unitalk AI Gateway managed by LiteLLM; no customer API key.'),('S6-2','Use deepseek-v4-flash as primary, routed by LiteLLM to Microsoft Azure.'),('S6-3','Use Gemini 3.7 Flash as one-shot technical fallback, routed by LiteLLM to Google.'),('S6-4','Use 4,000 maximum output tokens, 50 model iterations, one retry before fallback and medium reasoning.'),('S6-5','Enable only clarify, code execution, file, skills, terminal and todo in the local baseline.'),('S6-6','Keep Web, providers, Twenty, HubSpot, n8n, outreach and durable handoffs disabled.'),('S6-7','Allow Sales Lead, Sales Operations/CRM and Prospecting roles; keep named reviewers pending.'),('S6-8','Use the global Unitalk–Mustad USD 5,000 budget with 50/80/100 percent thresholds and no A2 allocation yet.'),('S6-9','Use local audit artifacts now; keep retention, admin visibility and external audit sink pending.'),('S6-10','Allow Step 6 promotion for synthetic local testing after a compliant primary response; keep upstream telemetry, fallback verification, provider regions and retention as mandatory gates before any real Mustad/Equinet data.')];rows='\n'.join(f'| {i} | {x} |' for i,x in decisions);REVIEW.write_text(f'''# Decision Review — Step 6 Model, Tools, Permissions and Quotas\n\n**Status:** `CONFIGURED — STATIC VALIDATION PASS — LIVE GATEWAY SMOKE PENDING`  \n**Profile:** `equinet-a2-enrichment`\n\n## Confirmed configuration\n\n- Primary: `deepseek-v4-flash` via Unitalk AI Gateway / LiteLLM / Microsoft Azure.\n- Fallback: `Gemini 3.7 Flash` via Unitalk AI Gateway / LiteLLM / Google.\n- Static checks: **{sum(checks.values())}/{len(checks)} PASS**.\n- External calls/actions during configuration: **0/0**.\n\n## Decisions\n\n| ID | Decision |\n|---|---|\n{rows}\n\n## Remaining gate\n\n{primary_note} A controlled fallback-route test is also required. Provider region, retention and DPA evidence remain pending.\n''')
 files=[CONFIG,POLICY,OUT,REVIEW,STEP5,DEFAULT,SMOKE_VALIDATOR]
 if PRIMARY_RESULT.exists():files.append(PRIMARY_RESULT)
 if PRIMARY_V2.exists():files.append(PRIMARY_V2)
 if PRIMARY_VALIDATION.exists():files.append(PRIMARY_VALIDATION)
 manifest={'manifest_id':'equinet-a2-step6-draft-package','version':'0.1.0-draft.1','status':result['status'],'files':[{'path':str(x.relative_to(ROOT)) if x.is_relative_to(ROOT) else str(x),'bytes':x.stat().st_size,'sha256':sha(x)} for x in files],'file_count':len(files),'static_checks':f"{sum(checks.values())}/{len(checks)} pass",'live_gateway_smoke':'pending','external_actions':0,'promotion_performed':False};MANIFEST.write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'pass':result['pass'],'static_checks':f"{sum(checks.values())}/{len(checks)}",'primary':result['model_routing']['primary'],'fallback':result['model_routing']['fallback'],'live_smoke':'pending','status':result['status'],'failures':failures},indent=2));return 0 if not failures else 1
if __name__=='__main__':raise SystemExit(main())
