# Terminal backend profile leakage: diagnostic example

## Symptom

A selected Hermes profile resolved `terminal.backend` as `local`, but terminal, file, and code-execution tools later failed with:

```text
SSH environment requires ssh_host and ssh_user to be configured
```

The failure appeared only after a long-running command timed out.

## Evidence pattern

The investigation separated the root/dashboard scope from the selected profile:

- root `config.yaml`: explicit `terminal.backend: ssh`;
- root `.env`: `TERMINAL_ENV=local`;
- selected profile `config.yaml`: no explicit `terminal` section, so `local` was only the merged default;
- SSH host/user were absent.

Because an explicit non-secret YAML setting wins over `.env`, the root runtime still owned `ssh`. The selected profile’s absent key did not reliably override an inherited process value.

A controlled reproduction proved the distinction:

```bash
HERMES_HOME=<selected-profile> TERMINAL_ENV=ssh <python> -c \
  "from tools.terminal_tool import _get_env_config; c=_get_env_config(); print(c['env_type'])"
```

Before mitigation, this printed `ssh`; after adding an explicit profile `terminal.backend: local`, the same poisoned-inheritance probe printed `local`.

## Why the failure was delayed

Logs showed:

1. a local environment was initially created;
2. the cached local environment continued serving commands;
3. it was later cleaned up / lost after a long command timeout;
4. recreation sampled the process-level SSH selection;
5. environment creation failed because SSH credentials were intentionally absent.

Therefore the timeout exposed the configuration leak; it was not the root cause.

## Implementation finding

The installed Hermes build bridged terminal config through process-wide `TERMINAL_*` variables. Its dashboard profile launch path applied launch-profile terminal configuration before switching `HERMES_HOME` to the selected profile. A newer source checkout reversed that order and removed only launch-profile-owned terminal variables before applying the selected profile; it also contained a regression test for selected-profile terminal bridging.

Treat this as version-specific evidence. Verify the running build before concluding that a deployment still has the defect.

## Safe mitigation used

Make the selected profile explicit:

```bash
HERMES_HOME=<selected-profile> hermes config set terminal.backend local
```

Then verify:

1. profile YAML contains `terminal.backend: local`;
2. `hermes config get terminal.backend` returns `local`;
3. the poisoned-inheritance probe returns `local`;
4. a real terminal command succeeds.

Do not add fake SSH credentials. Do not edit the root/default profile from a profile-scoped session without authorization.

## Deployment-level follow-up

If the root config is generated by a container entrypoint or deployment template, changing the live file alone may be overwritten on restart. Inspect only the relevant command/config fragment—never dump a full process command or environment because bootstrap arguments may contain secrets. Correct the deployment template and upgrade to a build with profile-scoped terminal bridging, then restart and repeat the verification sequence.
